name: Deploy to Hostinger

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 65002 145.223.106.133 >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no -p 65002 u522518288@145.223.106.133 'echo "SSH connection successful"'

      - name: Deploy to Hostinger
        run: |
          ssh -o StrictHostKeyChecking=no -p 65002 u522518288@145.223.106.133 "cd /home/u522518288/domains/creativecactuswebdesigns.com/public_html && git pull origin master"
